[0m[[0m[31merror[0m] [0m[0m/home/jay/projects/InsightHoot/InsightHoot/src/test/scala/simpletest/MyTests.scala:3:23: not found: value munit[0m
[0m[[0m[31merror[0m] [0m[0mclass MyTests extends munit.FunSuite {[0m
[0m[[0m[31merror[0m] [0m[0m                      ^[0m
[0m[[0m[31merror[0m] [0m[0m/home/jay/projects/InsightHoot/InsightHoot/src/test/scala/simpletest/MyTests.scala:4:3: not found: value test[0m
[0m[[0m[31merror[0m] [0m[0m  test("sum of two integers") {[0m
[0m[[0m[31merror[0m] [0m[0m  ^[0m
[0m[[0m[31merror[0m] [0m[0m/home/jay/projects/InsightHoot/InsightHoot/src/test/scala/simpletest/MyTests.scala:7:5: not found: value assertEquals[0m
[0m[[0m[31merror[0m] [0m[0m    assertEquals(obtained, expected)[0m
[0m[[0m[31merror[0m] [0m[0m    ^[0m
[0m[[0m[31merror[0m] [0m[0mthree errors found[0m
